#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

printusage() {
cat <<EOPU
Usage: 
       Encrypted TAR Compress
       Archives, zips, and encrypts files/directories
       GNU General Public License v3.0
       https://www.grc.com/passwords.htm for secure password info
       $(basename ${0}) -c target_file source_list
       $(basename ${0}) -d target_file 
       $(basename ${0}) -p 
Notes:
       -c compress encrypted tar file
       -d decompress encrypted tar file
       -p print key
EOPU
exit 100
}

if [ $# -eq 3 -a "${1}" == "-c" ]; then
   tar -czf - ${3} \
      | pv -s `du -bs ${3} | cut -f 1` \
      | openssl enc -e -aes256 -k `cat /tmp/.num` -out ${2}
elif [ $# -eq 2 -a "${1}" == "-d" ]; then
   openssl enc -d -aes256 -k `cat /tmp/.num` -in ${2} \
      | pv -s `du -bs ${2} | cut -f 1` \
      | tar xz
elif [ $# -eq 1 -a "${1}" == "-p" ]; then
   cat /tmp/.num 
else
   printusage
fi

# NOTES:
# https://www.grc.com/passwords.htm

